### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by fbrettnich** [fbrettnich/hcloud-snapshot-as-backup#4]
Make script available as Docker container for easier use

**Comment by ToshY** [comment]
@fbrettnich Are you still actively maintaining this project? 

I would be interested in having a Docker image for this.

**Comment by fbrettnich** [comment]
> @fbrettnich Are you still actively maintaining this project?
> 
> I would be interested in having a Docker image for this.

Is available now 👍
