### ISSUE TITLE
[Feature] Add human readable datetime format for snapshot names

### ISSUE THREAD

**Issue by ToshY** [fbrettnich/hcloud-snapshot-as-backup#6]
**Problem**

Currently you can name the snapshot with for example `%name%-%timestamp%` format. This will result in something like `new-server-1667887200`. The problem is, timestamps are not really that human friendly, as you just can't directly see what the date and time is when the snapshot was created.

**Proposed**

Allow user specified custom datetime format (using for example `strftime`), and fallback to timestamp as default to avoid breaking change.

**Comment by fbrettnich** [comment]
If you are in the Cloud Console, you can see the full date directly there
But we can add a new variable like `%date%` for that

Do you plan to open a pull request?

![image](https://user-images.githubusercontent.com/42101045/200892279-00415d8e-f9f5-4f47-9404-a4ab517e62a3.png)

**Comment by ToshY** [comment]
I totally missed that 🤦‍♂️ Thanks for taking the time to point that out. 

I will close the issue as I don't see a particular need for it now.

**Comment by fbrettnich** [comment]
@ToshY added `%date%` and `%time%` placeholder

**Comment by ToshY** [comment]
@fbrettnich Thank you for taking the effort 👍 I'm going to use them immediately 😄
